apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-assignment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-assignment
  template:
    metadata:
      labels:
        app: devops-assignment
    spec:
      containers:
        - name: devops-assignment
          image: ravikantbits.azurecr.io/devops-assignment:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: devops-assignment
spec:
  type: LoadBalancer
  ports:
    - port: 8080
  selector:
    app: devops-assignment
